name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      timeout-minutes: 10

    - name: Build package
      run: npm run build

    - name: Verify build output
      run: |
        ls -la dist/
        if [ ! -f "dist/index.js" ]; then
          echo "Build failed: dist/index.js not found"
          exit 1
        fi

    - name: Publish to npm
      if: ${{ secrets.NPM_TOKEN != '' }}
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## What's Changed

          See the [CHANGELOG](https://github.com/methodnumber13/asterdex-sdk/blob/main/CHANGELOG.md) for detailed changes.

          ## Installation

          ```bash
          npm install asterdex-sdk@${{ github.ref_name }}
          ```

          ## Documentation

          - [README](https://github.com/methodnumber13/asterdex-sdk#readme)
          - [API Documentation](https://github.com/methodnumber13/asterdex-sdk/blob/main/README.md#-complete-api-reference)